version: '3.8'

services:
  mysqldb:
    platform: linux/x86_64
    env_file:
      - ./.env
    image: mysql:5.7
    container_name: mysqldb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DB
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    
  app: 
    build: . 
    depends_on:
      - mysqldb
    links: 
      - mysqldb
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT