version: '3.8'

services:
  mysqldb:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: mysqldb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
    ports:
      - 3306:3306
    